---
title: "PoTSurveyAnalysis"
author: "Mark Walter"
date: "3/7/2021"
output: powerpoint_presentation
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("openxlsx")    # library("readxl") # this is the tidyverse installed package
library("scales")
library("lubridate")
library("googledrive")
library("googlesheets4")

#library("pastecs")
#library("anytime")

```

# Introduction

This document currently has just 2 parts. 

* Year of hire by quarter and then by current rank. 
* Distribution of Actual, Preferred and Expected Workload by Activity

```{r load_data, include=FALSE}
source(".././Script/Functions/ShowWorkMeans.r")

col_names <- names(read_csv(".././Data/Professor of Teaching Effort Distribution and Support Survey_February 24, 2021_21.37_NumChoice.csv", n_max = 0))
AllDataNumTib <- read_csv(".././Data/Professor of Teaching Effort Distribution and Support Survey_February 24, 2021_21.37_NumChoice.csv",
                          col_names = col_names, skip = 3)    # load all data
AllDataTextTib <- read_csv(".././Data/Professor of Teaching Effort Distribution and Support Survey_February 24, 2021_22.13_TextChoice.csv",
                          col_names = col_names, skip = 3)    # load all data

```

## Hire Year Data


```{r Hire_Year, echo=FALSE, fig.dim = c(10, 6)}
ggplot(data=AllDataTextTib, aes(x=Q1.3_2,fill=Q1.3_1),na.rm=TRUE) + 
 geom_bar(mapping=aes(x=Q1.3_2,fill=Q1.3_1),na.rm=TRUE)+
  labs(title="Hire Year/Quarter",x="Year")+
  scale_y_continuous(breaks=seq(0,20,2))+
  scale_x_continuous(breaks=seq(1990,2022,2))

# bar chart of start-date year with CURRENT rank stacking
ggplot(data=AllDataTextTib) + geom_bar(mapping=aes(x=Q1.3_2,fill=Q1.2))+
  labs(title="Hire Year/Current Rank",x="Year")+
  scale_y_continuous(breaks=seq(0,20,2))+
  scale_x_continuous(breaks=seq(1990,2022,2))
```


## Workload Distribution Data

...
# Plots
...


```{r All PoT, fig.dim = c(10, 6)}
subt <- "Workload Distribution: Expected, Desired, Actual"

p <- ShowWorkMeans("1==1")
p + scale_fill_brewer(palette="Greens") +
  labs(title=paste("All Pot (Count = ",count,")"), subtitle=subt)
```

```{r Since 2015, fig.dim = c(10, 6)}
p <- ShowWorkMeans('Q1.3_2>="2015"')    # greater than 2015
p + scale_fill_brewer(palette="Blues") +
  labs(title=paste("PoT Hired 2015 and Later (Count = ",count,")"), subtitle=subt)
```

```{r Before 2015, fig.dim = c(10, 6)}
p <- ShowWorkMeans('Q1.3_2<"2015"') # Less than 2015 
p + scale_fill_brewer(palette="Reds") +
  labs(title=paste("PoT Hired Before 2015 (Count = ",count,")"), subtitle=subt)
```

```{r Assistant PoT, fig.dim = c(10, 6)}
p <- ShowWorkMeans('Q1.2=="Assistant"')  # Assistant PoTs
p + scale_fill_brewer(palette="Oranges") +
  labs(title=paste("Assistant PoTs (Count = ",count,")"), subtitle=subt)
```

```{r Associate/Full PoT, fig.dim = c(10, 6)}
p <- ShowWorkMeans('Q1.2=="Full"|Q1.2=="Associate"')   # Full and Associate PoTs
p + scale_fill_brewer(palette="Purples") +
  labs(title=paste("Associate and Full PoTs (Count = ",count,")"), subtitle=subt)
```


